# netlify.toml

[build]
  # La commande à exécuter pour builder votre projet (si nécessaire)
  command = "npm run build"
  
  # Le dossier où les fichiers construits seront stockés pour être déployés
  publish = "build"  # Changez le dossier selon où votre build est généré

[context.production.environment]
  # Les variables d'environnement spécifiques à la production
  NODE_ENV = "production"